slack test

diff --git a/.github/workflows/slack.yaml b/.github/workflows/slack.yaml
--- a/.github/workflows/slack.yaml
+++ b/.github/workflows/slack.yaml
@@ -8,11 +8,11 @@ jobs:
     Slack:
         runs-on: ubuntu-latest
         steps:
-            # - name: Test Success
-            #   run: echo "hello world"
+            - name: Test Success
+              run: echo "hello world"
 
-            - name: Test Failure
-              run: exit 1
+            # - name: Test Failure
+            #   run: exit 1
 
             - name: If Actions Failure
               if: ${{failure()}}
